name: Run Python Script and Commit SVG

on:
  push:
    branches:
      - main

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' #really?

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python test.py

    - name: Touch README
      run: touch README.md

    - name: Commit and push changes
      run: |
        git config --local user.email "test@github.com"
        git config --local user.name "GitHub Action test"
        git add test.svg README.md
        git commit -m 'Update test.svg'
    - name: Push changes
      uses: ad-m/github-push-action@master #seems sketchy
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
